version: '3'
services:
  service: &default
    build: .
    depends_on:
      - redis
    environment:
      - CACHE_HOST=redis
      - CACHE_PORT=6379
      - MYSQL_HOST=
      - MYSQL_PORT=3306
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app
      - ./tests:/usr/src/tests
      - ./requirements.txt:/usr/local/airflow/requirements.txt
    links:
      - redis
    command: python app/main.py

  redis:
    image: "redis:5.0-rc6"
    ports:
      - "6379:6379"
